import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync } from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const copyWasmPlugin = {
	name: 'copy-wasm',
	setup(build) {
		build.onEnd(() => {
			const src = './node_modules/sql.js/dist/sql-wasm.wasm';
			const dest = './sql-wasm.wasm';
			if (existsSync(src)) {
				copyFileSync(src, dest);
				console.log('[copy-wasm] sql-wasm.wasm copied to output');
			} else {
				console.error('[copy-wasm] sql-wasm.wasm NOT FOUND — DB will fail to load');
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner + '\nvar importMetaUrl = require("url").pathToFileURL(__filename).href;\n',
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	define: {
		'import.meta.url': 'importMetaUrl',
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	loader: {
		'.wasm': 'file',
	},
	plugins: [copyWasmPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
